version: '2'
services:
    blogchain-app:
        image: blogchain
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://blogchain-postgresql:5432/blogchain
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blogchain-postgresql:
        extends:
            file: postgresql.yml
            service: blogchain-postgresql
